#!/usr/bin/env python3
import os
import sys
import argparse
import re
import math
from fractions import Fraction

whoami = os.path.basename(sys.argv[0])


class _Main:
    def main(self, args=sys.argv[1:], prog=whoami):
        options = self.parse_args(args, prog)
        self.top(options)

    def parse_args(self, args, prog):
        parser = argparse.ArgumentParser(
            prog=prog,
            description=(
                'Find pitch exponents close to ratios or the other way around'
            ),
        )
        parser.add_argument('value',
                            help='ratio (a/b) or exponent (^a|b)')
        parser.add_argument('--max-denominator',
                            help='maximum denominator of fraction')
        return parser.parse_args(args)

    @staticmethod
    def edo_deviation(val, target):
        return math.log(val/target, 2) * 1200

    @staticmethod
    def log_deviation(val, target):
        return 1200 * (val - target)

    @staticmethod
    def find_matches(target, max_denom, max_deviation, deviation_fn):
        results = []
        seen = set()

        for den in range(2, max_denom + 1):
            # Find the closest numerator for this denominator
            num = round(target * den)
            val = num / den
            deviation = deviation_fn(val, target)
            if abs(deviation) < max_deviation:
                f = Fraction(num, den)
                if f not in seen:
                    seen.add(f)
                    results.append((f, deviation))

        results.sort(key=lambda x: abs(x[1]))
        return results

    def top(self, options):
        m = re.fullmatch(r'(\^(\d+)\|(\d+))|((\d+)/(\d+))', options.value)
        if m is None:
            exit('value must be a/b or ^a|b')
        exp = m[1]
        ratio = m[4]
        max_denom = (None if options.max_denominator is None
                     else int(options.max_denominator))
        if exp is not None:
            # We want a ratio that is close to the exponent. Convert
            # the exponent to a regular pitch ratio. Results are also
            # regular pitch ratios. The denominator represents an
            # offset in the harmonic sequence.
            if max_denom is None:
                max_denom = 32
            num = int(m[2])
            den = int(m[3])
            goal = 2 ** (Fraction(num, den))
            goal_str = exp
            best_matches = self.find_matches(goal, max_denom, 16, self.edo_deviation)
            best_matches = [(v, d, v) for (v, d) in best_matches]
        elif ratio is not None:
            # We want an exponent that is close to the ratio. To find
            # the x such that 2^x is closest to a value, we find x
            # that's closest to log_2(value). Since we are working in
            # a logarithmic scale, we use subtraction to determine the
            # deviation.
            if max_denom is None:
                max_denom = 53
            num = int(m[5])
            den = int(m[6])
            goal = Fraction(num, den)
            goal_str = ratio
            best_matches = self.find_matches(
                math.log2(goal), max_denom, 16, self.log_deviation)
            best_matches = [
                (2 ** v, d, (v.numerator, v.denominator))
                for (v, d) in best_matches
            ]
        print(f'goal={goal_str} =~ {goal:6f}')
        for (best, cents, best_str) in best_matches:
            equiv = ''
            if ratio is not None:
                # Generate a list of non-simplified fractions for
                # easier search.
                (n, d) = best_str
                best_str = f'^{n}|{d}'
                i = 2
                other = []
                while d * i <= max_denom:
                    other.append(f'^{n*i}|{d*i}')
                    i += 1
                if other:
                    equiv = ' (' + ', '.join(other) + ')'
            print(f'  {best_str} =~ {best:6f}, delta =~ {cents:6f}¢{equiv}')


if __name__ == '__main__':
    try:
        _Main().main()
    except KeyboardInterrupt:
        exit(130)
