#!/usr/bin/env python3
import math
import fractions

# Find all ratios 1+b/a where 15/13 <= 1+b/a <= 16/13 and 1 <= b <= 9
# in numerical order. This generates the ratios used in Fabio Costa's
# Etude on Minor Thirds: https://www.youtube.com/watch?v=U7l7s1Vr6lQ
# Then generate scales for each and a layout for each in sets of 8.

min_frac = 2.0/13.0
max_frac = 3.0/13.0

items = set()
next_i = 1
while True:
    i = next_i
    next_i += 1
    min_delta = math.ceil(min_frac * i)
    max_delta = math.floor(max_frac * i)
    if max_delta < 1:
        continue
    if min_delta > 9:
        break
    for j in range(min_delta, 1+max_delta):
        if j > 9:
            break
        items.add(fractions.Fraction(i+j, i))

ratios = sorted(items)

all_names = []
all_notes = []
for r in ratios:
    (a, b) = r.as_integer_ratio()
    delta = a - b
    names = []
    lowest = 0
    while a > 0 and len(names) < 8:
        names.append(str(a))
        lowest = a
        a -= delta
    while len(names) < 8:
        names.append('')
    notes = [f'{x}/{b}' if x != '' else '' for x in names]
    if names[7] == '' and lowest > 1:
        names[7] = '(1)'
        notes[7] = f'1/{b}'
    all_names.append(names)
    all_notes.append(notes)

empty_8 = list(['' for i in range(8)])
empty_64 = list(['' for i in range(64)])
while len(all_notes) % 8 != 0:
    all_notes.append(empty_8)
    all_names.append(empty_8)

print('# Scales from Fabio Costa\'s Etude on Minor Thirds in order')
print('# There are some extra ones that aren\'t in the video.')
print('# https://www.youtube.com/watch?v=U7l7s1Vr6lQ')
print('# Generated by misc/minor-thirds.py')
count = 1
while len(all_notes) > 0:
    # Transpose from row-based to column-based
    name_group = all_names[0:8]
    note_group = all_notes[0:8]
    all_names = all_names[8:]
    all_notes = all_notes[8:]
    scale_notes = []
    scale_names = []
    for row in range(8):
        notes = []
        names = []
        for col in range(8):
            notes.append(note_group[col][row])
            names.append(name_group[col][row])
        scale_notes.append(notes)
        scale_names.append(names)
    scale = f'"Minor Thirds {count}"'
    count += 1
    print('[[scale]]')
    print(f'name = {scale}')
    print('type = "Generic"')
    print('base_pitch = "880*^1|6"')
    print('pitches = [')
    for row in scale_notes:
        print(', '.join([f'"{x}"' for x in row]) + ',')
    print(']')
    print('note_names = [')
    for row in scale_names:
        print(', '.join([f'"{x}"' for x in row]) + ',')
    print(']')
    print('[[layout]]')
    print(f'name = {scale}')
    print(f'scale_name = {scale}')
