#!/usr/bin/env python3
import math
import fractions

# Find all ratios 1+b/a where 15/13 <= 1+b/a <= 16/13 and 1 <= b <= 9
# in numerical order. This generates the ratios used in Fabio Costa's
# Etude on Minor Thirds: https://www.youtube.com/watch?v=U7l7s1Vr6lQ
# Then generate scales for each and a layout for each in sets of 8.

min_frac = 2.0/13.0
max_frac = 3.0/13.0

items = set()
next_i = 1
while True:
    i = next_i
    next_i += 1
    min_delta = math.ceil(min_frac * i)
    max_delta = math.floor(max_frac * i)
    if max_delta < 1:
        continue
    if min_delta > 9:
        break
    for j in range(min_delta, 1+max_delta):
        if j > 9:
            break
        items.add(fractions.Fraction(i+j, i))

ratios = sorted(items)

all_notes = []
for r in ratios:
    (a, b) = r.as_integer_ratio()
    delta = a - b
    notes = []
    lowest = 0
    while a > 0 and len(notes) < 8:
        notes.append((a, b))
        lowest = a
        a -= delta
    if len(notes) < 8 and lowest > 1:
        notes.append((1, b))
    all_notes.append(notes)

print('''; Scales from Fabio Costa's Etude on Minor Thirds in order
; There are some extra ones that aren't in the video.
; https://www.youtube.com/watch?v=U7l7s1Vr6lQ
; Generated by misc/minor-thirds.py

syntoniq(version=1)
set_base_pitch(absolute=880*^1|6)
''')

mappings=[]
for notes in all_notes:
    (a, b) = notes[0]
    name = f'{a}/{b}'
    print(f'define_scale(scale="{name}") <<')
    for (i, (a, b)) in enumerate(notes):
        print(f'{a}/{b} h{a}', end='')
        if i == 3 or i == len(notes) - 1:
            print('')
        else:
            print(' |', end='')
    print('>>')
    print(f'define_manual_mapping(scale="{name}" mapping="{name}") <<')
    for (i, (a, b)) in enumerate(notes):
        if i == 1:
            print('@', end='')
        print(f'h{a}')
    print('>>')
    mappings.append((name, len(notes)))

for (i, (mapping, height)) in enumerate(mappings):
    page = 1 + int(i / 8)
    anchor_col = 1 + (i % 8)
    rows_below = height - 2
    print('place_mapping(')
    print(f'    layout="page{page}"')
    print(f'    mapping="{mapping}"')
    print('    keyboard="launchpad"')
    print('    anchor_row=7')
    print(f'    anchor_col={anchor_col}')
    print('    cols_left=0')
    print('    cols_right=0')
    print('    rows_above=1')
    print(f'    rows_below={rows_below}')
    print(')')
