version: '3'

tasks:
  default:
    deps:
      # Every *-csound.mp3 file included in the docs can be generated
      # from a *.stq file in this directory. They have to be
      # explicitly added here. Currently, *-mpe.mp3 and *-mts.mp3 are
      # manually generated.
      - stq-csound-mp3:110-to-880hz
      - stq-csound-mp3:440-to-660hz
      - stq-csound-mp3:440hz
      - stq-csound-mp3:harmonic-1-to-12
      - stq-csound-mp3:hello
      - stq-csound-mp3:major-thirds
      - stq-csound-mp3:5-edo-pqrst
      - stq-csound-mp3:13-ed3
      - stq-csound-mp3:ji-sample-12-edo
      - stq-csound-mp3:ji-sample
      - stq-csound-mp3:ji-sample-41-edo
      - built-in-scales
      - directives
    cmds:
      - ../autogen

  stq-csound-mp3:*:
    cmds:
      - "../../target/debug/syntoniq generate --score={{index .MATCH 0}}.stq --csound={{index .MATCH 0}}.csd"
      - "csound --wave -o {{index .MATCH 0}}.wav {{index .MATCH 0}}.csd"
      - "lame -V 0 -h {{index .MATCH 0}}.wav ../static/{{index .MATCH 0}}-csound.mp3"
      - "rm {{index .MATCH 0}}.wav {{index .MATCH 0}}.csd"
    sources:
      - ./{{index .MATCH 0}}.stq
    generates:
      - ../static/{{index .MATCH 0}}-csound.mp3

  built-in-scales:
    cmds:
      - "cp ../../common/src/parsing/built-in-scales.stq ."
    sources:
      - ../../common/src/parsing/built-in-scales.stq
    generates:
      - built-in-scales.stq

  directives:
    cmds:
      - "../../target/debug/syntoniq doc > directive_doc.md"
    sources:
      - ../../common/src/parsing/score/directives.rs
      - ../../common/directive_derive/src/lib.rs
    generates:
      - directive_doc.md
