#!/bin/bash
set -eo pipefail
cd $(dirname $0)
cargo fmt
cargo clippy --no-deps
cargo clippy --tests --no-deps
# Avoid --document-private-items -- generates warnings with csound docs
cargo doc --no-deps
cargo build --workspace --all-targets "$@"
./manual/build
export RUST_BACKTRACE=1
cargo test --workspace "$@"
