# https://taskfile.dev

version: '3'

env:
  CLICOLOR_FORCE: 1

tasks:
  build:
    desc: "Run development build"
    cmds:
      - ./build.sh
    silent: true

  coverage:
    desc: "Run coverage build and coverage testing"
    cmds:
      - ./coverage.sh
    silent: true

  manual-serve:
    desc: "Serve manual for editing"
    dir: manual
    cmds:
      - zola serve

  manual-build:
    desc: "Build manual"
    dir: manual
    cmds:
      - zola build
